version: "3.8"
services:
  app:
    container_name: portfolio-v3
    image: portfolio-v3
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
